package com.oryfolks.lms_backend.entity;

public enum NotificationType {
    COURSE_ASSIGNED,
    DEADLINE_REMINDER,
    ENROLLMENT_APPROVED,
    ENROLLMENT_REJECTED,
    ASSIGNMENT_GRADED,
    NEW_CONTENT_ADDED,
    PASSWORD_CHANGED,
    
    // Manager Notification Types
    ENROLLMENT_REQUEST_RECEIVED,
    COURSE_COMPLETION,
    DEADLINE_MISSED,
    COURSE_ASSIGNMENT_CONFIRMATION,
    
    // Admin Action Types
    NEW_COURSE_ADDED,
    NEW_EMPLOYEE_ADDED,

    // Admin Notification Types
    SYSTEM_ERROR,
    USER_CREATED,
    USER_DELETED,
    COURSE_CREATED,
    COURSE_DELETED,
    BULK_IMPORT_COMPLETED,
    BULK_UPLOAD_FAILED,
    SECURITY_ALERT,
    DAILY_ENROLLMENT_SUMMARY,
    HIGH_ACTIVITY_ALERT,
    MANAGER_PENDING_APPROVAL
}
