spring.config.import=optional:file:.env[.properties]
spring.application.name=lms-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_BUCKET_NAME}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1

azure.activedirectory.tenant-id=${AZURE_TENANT_ID}
azure.activedirectory.client-id=${AZURE_CLIENT_ID}
azure.activedirectory.client-secret=${AZURE_CLIENT_SECRET}
azure.activedirectory.sender-email=${AZURE_SENDER_EMAIL}
app.frontend-url=${FRONTEND_URL:http://localhost:5173}
